#!/bin/sh

get_github_url () {
	github_url=`git remote -v | grep git@github.com | grep fetch | head -1 | cut -f2 | cut -d' ' -f1 | sed -e's/:/\//' -e s/'git@/http:\/\//' -e s/'\.git//'`
	escaped_file=$(python -c "import urllib, sys; print urllib.quote(sys.argv[1])"  "$1")
	echo "$github_url/blob/master/$escaped_file"
}

title="# Swift Playground for [Advent of Code](https://adventofcode.com) challenges"
echo $title > README.md

subtitle="### This file is automatically generated by generate-readme.sh"
echo $subtitle >> README.md

page_title_regex="Pages\/(.*)\.xcplaygroundpage"
find * -name "*.swift" -print | sort -V | while read swift_file; do
	if [[ $swift_file =~ $page_title_regex ]]
	then
		title="${BASH_REMATCH[1]}"
		swift_file_github_url=`get_github_url "$swift_file"`
		file_markdown="[${title}](${swift_file_github_url})\n"
		echo $file_markdown >> README.md
	fi
done
